### ISSUE TITLE
Authentication menu item doesn't seen

### ISSUE THREAD

**Issue by ngulesanlar** [qwc-services/qwc-docker#21]
I follow all instructions in the document but Login and Logout menu items doesn't seen.

```
sed -e '/proxyServiceUrl/d' \
  -e 's!permalinkServiceUrl":\s*".*"!permalinkServiceUrl": "/permalink"!' \
  -e 's!elevationServiceUrl":\s*".*"!elevationServiceUrl": "/elevation"!' \
  -e 's!searchServiceUrl":\s*".*"!searchServiceUrl": "/search"!' \
  -e 's!editServiceUrl":\s*".*"!editServiceUrl": "/data"!' \
  -e 's!authServiceUrl":\s*".*"!authServiceUrl": "/auth"!' \
  -e 's!mapInfoService":\s*".*"!mapInfoService": "/mapinfo"!' \
  -e 's!featureReportService":\s*".*"!featureReportService": "/document"!' \
  -e 's!{"key": "Login", "icon": "img/login.svg"}!{{ login_logout_item }}!g' \
  config.json > $DSTDIR/qwc2/config.json

```
some of these lines are missing in the config.json;
There already are no some of these lines in the config.json of qwc2-demo-app  file. So I add these lines in this file (eg. `{{ login_logout_item }}` ) but Login menu item doesn't seen.
Thanks.

**Comment by HusseinKabbout** [comment]
You cannot log out directly from the AdminGUI, you have to use the Logout Menu Item in QWC2. In order for the login / logout entries to appear, they must be available in the config.json as {"key": "Login", "icon": "login"} under menuItems. The authentication plugin must also be activated. In the example of the qwc2-demo-app, however, this is not activated.

**Comment by HusseinKabbout** [comment]
In order for the login / logout entries to appear, they must be present in the `config.json` file as {"key": "Login", "icon": "login"} under menuItems. The authentication plugin must also be activated. In the example of the qwc2 demo app, however, this is not activated.

**Comment by HusseinKabbout** [comment]
This issue will be closed, because the problem seems to be a misconfiguration on the users side. If anyone encounters the same "problem" then please read my comment and if the login/logout menu item doesn't appear then please reopen this issue.

**Comment by 8ern4ard** [comment]
hello, 
 i can login/logout with the direct links (http://localhost:8088/auth/login) and the status is reflected in my map viewer, eg the menu entry would show "logout" when i already logged in before. however, when i click the regarding menu entry in the map viewer, i am not forwarded to the login gui but just nothing happens on click. what am i missing? 

* no docker log entries on click. 
* i updated the configs with sudo curl -X POST "http://localhost:5010/generate_configs?tenant=default". 

i tried to find the solution in the sogis viewer repo and copied the  {"key": "Login", "icon": "login"} menu entries to mobile/desktop based on that. i figured the autologin and loginuser config entries in sogis must be for something project-specific, so i didn't use that. 

my setup is on an aws instance with all ports mentioned (specifically 5017, i guess) in the readme open for inbound traffic and i use the containers as explained in this (qwc-docker) repo.

what boggles me as well, is the sed command: 
-e 's!{"key": "Login", "icon": "img/login.svg"}!{{ login_logout_item }}!g' \
would actually substitute the key/icon dict for a {{ login_logout_item }} blob, right? 
the config generator would then complain: 
CRITICAL: Could not load QWC2 config.json:
Expecting property name enclosed in double quotes: line 336 column 18 (char 9624)

hope somebody can help, because it really bugs me not to get it ;)
thanks
