### ISSUE TITLE
arm64 supported images

### ISSUE THREAD

**Issue by yidnek-tibebu** [qwc-services/qwc-docker#56]
Hi

Is it possible to have arm64 versions of the images used in this repo?

**Comment by tpo** [comment]
Hi @yidnek-tibebu 

I am not the main driver behind the qwc-docker project, so my statement is not of much weight. However, AFAIK nobody at Sourcepole currently has access to a ARM64 server on which to develop and test arm64 versions of QWC2. So I think nobody at Sourcepole will do it at this time. That's why I'll close this ticket with "won't fix". However if anybody feels like they want to do it then I think s/he is very much welcome to do so and to follow up here in this ticket.
